---
apiVersion: v2
name: harbor-bootstrap
version: 0.1.0
description: Harbor Registry with DockerHub caching
dependencies:
  - name: harbor
    version: "1.18.2"
    repository: https://helm.goharbor.io
