---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wakapi
  namespace: apps
spec:
  selector:
    matchLabels:
      app: wakapi
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: wakapi
    spec:
      containers:
        - name: wakapi
          image: ghcr.io/muety/wakapi:2.16.1
          env:
            - name: WAKAPI_PORT 
              value: "3000"
            - name: WAKAPI_DISABLE_FRONTPAGE
              value: "true"
            - name: WAKAPI_ALLOW_SIGNUP
              value: "false"
            - name: WAKAPI_OIDC_ALLOW_SIGNUP
              value: "true"
            - name: WAKAPI_LEADERBOARD_ENABLED
              value: "false"
            - name: WAKAPI_PUBLIC_URL
              value: "https://wakapi.local.ildoc.it"

            - name: WAKAPI_OIDC_PROVIDERS_0_NAME
              value: "authentik"
            - name: WAKAPI_OIDC_PROVIDERS_0_DISPLAY_NAME
              value: "Authentik"
            - name: WAKAPI_OIDC_PROVIDERS_0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: oidc_client_id
            - name: WAKAPI_OIDC_PROVIDERS_0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: oidc_client_secret
            - name: WAKAPI_OIDC_PROVIDERS_0_ENDPOINT
              value: "https://auth.ildoc.it/application/o/wakapi/"


            - name: WAKAPI_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: password_salt
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              cpu: 50m
              memory: 500Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wakapi
