---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-wakapi-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: wakapi-secrets
    creationPolicy: Owner
  data:
  - secretKey: password-salt
    remoteRef:
      key: kubernetes/data/apps/wakapi
      property: password_salt
  