---
services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest@sha256:3bba0a99bc6e635bb8e53f379d32ab9cecb554adee9cc8f59a347f93ecf82f3b
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
