---
services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest@sha256:980e11fed03b8e7851e579be9f34b1210f516c9f0b4da1a1457f21a460bd6628
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
