gitlab:
  domain: gitlab.local.ildoc.it
  letsencrypt_email: "{{ _secrets.gitlab.letsencrypt_email }}"
  cloudflare_token: "{{ _secrets.gitlab.cloudflare_token }}"
  cleanup:
    interval_hours: 6
    aggressive_hour: 2
    disk_threshold: 85
    prune_until_hours: 24
    max_builds: 10
