invidious:
  db_user: invidious_user
  db_password: "{{ _secrets.invidious.db_password }}"
  db_name: invidious_db
  db_host: "192.168.0.30"
  visitor_data: "{{ _secrets.invidious.visitor_data }}"
  po_token: "{{ _secrets.invidious.po_token }}"
  hmac_key: "{{ _secrets.invidious.hmac_key }}"
  companion_key: "{{ _secrets.invidious.companion_key }}"
