---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: stunnel-gateway
  namespace: apps
spec:
  selector:
    istio: external-gateway
  servers:
    - port:
        number: 9443
        name: tcp-stunnel
        protocol: TCP
      hosts:
        - "*"
