---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-stunnel-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: stunnel-secrets
    creationPolicy: Owner
  data:
    - secretKey: wireguard-target
      remoteRef:
        key: kubernetes/data/apps/stunnel
        property: wireguard_target
