---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: stunnel-routing
  namespace: apps
spec:
  hosts:
    - "*"
  gateways:
    - stunnel-gateway
  tcp:
    - match:
        - port: 9443
      route:
        - destination:
            host: stunnel
            port:
              number: 443
