---
services:
  vault:
    image: hashicorp/vault:1.21.3@sha256:5f244d447c6f90107149c9565da5ffedf847cec673ba0062a82fc3dd83c89e65
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/file
      - ./init-vault.sh:/init-vault.sh
    cap_add:
      - IPC_LOCK
    command: "vault server -config=/vault/config/vault-config.json"
    restart: unless-stopped
