---
apiVersion: v2
name: prometheus-stack-bootstrap
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "80.13.2"
    repository: https://prometheus-community.github.io/helm-charts
