---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-sing-box-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: sing-box-secrets
    creationPolicy: Owner
  data:
    - secretKey: client-uuid
      remoteRef:
        key: kubernetes/data/apps/sing-box
        property: client_uuid
    - secretKey: gateway-address
      remoteRef:
        key: kubernetes/data/apps/sing-box
        property: gateway_address
    - secretKey: gateway-port
      remoteRef:
        key: kubernetes/data/apps/sing-box
        property: gateway_port
