---
apiVersion: v1
kind: Service
metadata:
  name: sing-box
  namespace: apps
  annotations:
    io.cilium/lb-ipam-ips: "192.168.0.83"
spec:
  type: LoadBalancer
  ports:
    - port: 9443
      targetPort: 443
      protocol: TCP
  selector:
    app: sing-box
