---
- name: Load secrets from Vault
  hosts: localhost
  gather_facts: false
  vars:
    vault_secrets_map:
      gitlab:
        letsencrypt_email: "ansible/data/gitlab:letsencrypt_email"
        cloudflare_token: "ansible/data/gitlab:cloudflare_token"
  
  tasks:
    - name: Include vault secrets loading task
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/vault/load-secrets.yaml"

- name: Configure gitlab with traefik
  hosts: gitlab
  gather_facts: true
  vars:
    _secrets: "{{ hostvars['localhost']['vault_secrets_loaded'] }}"
  
  roles:
    - role: gitlab
