---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-adventurelog-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: adventurelog-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: kubernetes/data/apps/adventurelog
      property: postgres_password
  - secretKey: secret-key
    remoteRef:
      key: kubernetes/data/apps/adventurelog
      property: secret_key
  - secretKey: admin-username
    remoteRef:
      key: kubernetes/data/apps/adventurelog
      property: admin_username
  - secretKey: admin-password
    remoteRef:
      key: kubernetes/data/apps/adventurelog
      property: admin_password
  - secretKey: admin-email
    remoteRef:
      key: kubernetes/data/apps/adventurelog
      property: admin_email