---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  namespace: apps
spec:
  selector:
    matchLabels:
      app: bentopdf
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
        - name: bentopdf
          image: bentopdf/bentopdf-simple:v1.7.9@sha256:0eb388c26deb0bf5bc2cb4909c72630fa3ea62354cddf5b4d5f347e62b59d33a
          resources:
            limits:
              cpu: 50m
              memory: 500Mi
