---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  namespace: apps
spec:
  selector:
    matchLabels:
      app: bentopdf
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
        - name: bentopdf
          image: bentopdf/bentopdf-simple:v1.7.4
          resources:
            limits:
              cpu: 50m
              memory: 500Mi
