---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  namespace: apps
spec:
  selector:
    matchLabels:
      app: bentopdf
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
        - name: bentopdf
          image: bentopdf/bentopdf-simple:v1.15.4@sha256:ed728002dede243e99da3b5f66a88ef4aa842962d5fc1313a75ab841cc9af237
          resources:
            limits:
              cpu: 50m
              memory: 500Mi
