---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  namespace: apps
spec:
  selector:
    matchLabels:
      app: bentopdf
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
        - name: bentopdf
          image: bentopdf/bentopdf-simple:v1.11.2@sha256:36ff37a6cee580a912cba423090324a909f098ad5d5213cfafbd15846ee268ee
          resources:
            limits:
              cpu: 50m
              memory: 500Mi
