{{- if .Values.outpost.enabled }}
---
# Deployment per Authentik Proxy Outpost
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-proxy-outpost
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: {{ .Values.outpost.replicas | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-proxy-outpost
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-proxy-outpost
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: proxy
        image: ghcr.io/goauthentik/proxy:{{ .Values.outpost.image.tag | default .Chart.AppVersion | default "2025.10.2" }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9443
          name: https
          protocol: TCP
        env:
        - name: AUTHENTIK_HOST
          value: "http://authentik-server.{{ .Release.Namespace }}.svc.cluster.local/"
        - name: AUTHENTIK_INSECURE
          value: "true"
        - name: AUTHENTIK_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentik-outpost-token
              key: token
        resources:
          {{- toYaml (.Values.outpost.resources | default dict) | nindent 10 }}
      {{- with .Values.outpost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
# Service per Authentik Proxy Outpost
apiVersion: v1
kind: Service
metadata:
  name: authentik-proxy-outpost
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: authentik-proxy-outpost
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
