---
services:
  gitlab:
    image: gitlab/gitlab-ce:18.6.1-ce.0@sha256:4a1765618d5b3aea9f9ae5efdb4f15a1880f0cab16801116f99c611080945c56
    container_name: gitlab
    hostname: 'gitlab'
    ports:
      - '80:80'
      - '22:22'
      - '5000:5000'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/entrypoint.sh:/entrypoint.sh
    command: ["/entrypoint.sh"]
    shm_size: '256m'
    restart: unless-stopped

  # runner:
  #   image: 'gitlab/gitlab-runner:latest'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./runner:/etc/gitlab-runner
  #   restart: always
  #   environment:
  #     - DOCKER_HOST=unix:///var/run/docker.sock

  nginx:
    image: nginx:stable@sha256:3048d7a6bad5fb1a1a2516249e570b85645a00411bad6b3126983577f040bb5f
    container_name: nginx
    depends_on:
      - gitlab
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    restart: always

  docker-cleanup:
    image: docker:latest@sha256:9b20eb23e1f0443655673efb9db76c4b18cc1b45de1fcf82b3c1b749b9647bdf
    container_name: docker-cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CLEANUP_INTERVAL=86400  # 24 ore in secondi
      - PRUNE_UNTIL=24h          # Rimuovi immagini piÃ¹ vecchie di 24 ore
    command: >
      sh -c "
        echo 'Docker cleanup service started';
        while true; do
          echo 'Running cleanup at' $$(date);
          docker system prune -af --filter 'until=$${PRUNE_UNTIL}' --volumes;
          docker image prune -af --filter 'until=$${PRUNE_UNTIL}';
          docker container prune -f --filter 'until=$${PRUNE_UNTIL}';
          docker volume prune -f;
          echo 'Cleanup completed. Sleeping for $${CLEANUP_INTERVAL} seconds';
          sleep $${CLEANUP_INTERVAL};
        done
      "
    restart: unless-stopped
