---
# ExternalSecret dedicato alle credenziali DEX/OIDC di ArgoCD
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex-secrets
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-dex-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      type: Opaque
      engineVersion: v2
      data:
        dex.authentik.clientSecret: "{{ .clientSecret }}"
  data:
  - secretKey: clientSecret
    remoteRef:
      key: kubernetes/data/infra/argocd
      property: dex-client-secret
